### ISSUE TITLE
Issues about variable failure

### ISSUE THREAD

**Issue by BingYanchi** [SimplyRin/BungeeFriends#13]
In the prompt message when the player is forced to add a friend, the variable cannot be converted normally.

https://user-images.githubusercontent.com/8200789/60782658-2fb53e80-a17a-11e9-8065-3c4adb6b8bb0.png

**Comment by SimplyRin** [comment]
We have released a new update.
Please check if the above bug has been fixed by that person.
The developer has confirmed that it works properly.
https://www.spigotmc.org/resources/bungeefriends.59256/update?update=287423

![0](https://i.gyazo.com/552c3814f7bc15af21cb9e651264c0e0.png "0")

**Comment by BingYanchi** [comment]
Thanks.
This is a great plugin.
